export const cars = [
    {
        id: 1,
        name: "Nissan Navarra",
        price: "900k",
        location: "Cau Giay, Hanoi",
        img1: "https://i.ex-cdn.com/vietnamfinance.vn/files/f1/news/ledinhnga/2020/11/5/Nissan-Navara-2021-5-2.jpg",
        img2: "https://i.ex-cdn.com/vietnamfinance.vn/files/f1/news/ledinhnga/2020/11/5/Nissan-Navara-2021-9-3.jpg",
        img3: "https://i.ex-cdn.com/vietnamfinance.vn/files/f1/news/ledinhnga/2020/11/5/VNF-Nissan-Navara-2021-ra-mat2.jpeg",
        licensePlates: "29A-2222",
        brandName: "Nissan",
        productionYear: 2021,
        transmission: true,
        color: "Black",
        model: "Navarra",
        noOfSeats: 5,
        fuel: true,
        registrationPaper: "File1.PDF",
        certificateOfInspection: "File2.PDF",
        insurance: null,
        mileage: 15000,
        fuelConsumption: 500,
        address: "Hanoi, Mai Dich, Cau Giay",
        description: "Nissan Navarra",
        functionsBluetooth: true,
        functionsGPS: false,
        functionsCamera: true,
        functionsSunRoof: false,
        functionsChildLock: true,
        functionsChildSeat: true,
        functionsDVD: false,
        functionsUSB: true,
        basePrice: 10000,
        requiredDeposit: 2000,
        noSmoking: true,
        noPet: true,
        noFoodInCar :false,
        other: false
    },
    {
        id: 2,
        name: "Toyota Camry",
        price: "700k",
        location: "Quan 1, Ho Chi Minh",
        img1: "https://www.toyota.com.vn//Resources/Images/F8B33019CF708D9157E8B8F633DDB447.png",
        img2: "https://www.toyota.com.vn//Resources/Images/EAE5157BACA728E302C7A2DB2D10B178.jpg",
        img3: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8bmF0dXJlfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
        licensePlates: "29A-2223",
        brandName: "Toyota",
        productionYear: 2023,
        transmission: true,
        color: "Black",
        model: "Camry",
        noOfSeats: 4,
        fuel: false,
        registrationPaper: "File1.PDF",
        certificateOfInspection: "File2.PDF",
        insurance: null,
        mileage: 15000,
        fuelConsumption: 500,
        address: " Ho Chi Minh, Quan 1, Khu 1",
        description: "Toyota Camry",
        functionsBluetooth: true,
        functionsGPS: false,
        functionsCamera: true,
        functionsSunRoof: false,
        functionsChildLock: false,
        functionsChildSeat: false,
        functionsDVD: false,
        functionsUSB: false,
        basePrice: 15000,
        requiredDeposit: 7000,
        noSmoking: true,
        noPet: true,
        noFoodInCar :false,
        other: false
    },
    {
        id: 3,
        name: "Toyota Camry",
        price: "1000k",
        location: "Hoang Mai, Hanoi",
        img1: "https://www.toyota.com.vn//Resources/Images/F8B33019CF708D9157E8B8F633DDB447.png",
        img2: "https://www.toyota.com.vn//Resources/Images/EAE5157BACA728E302C7A2DB2D10B178.jpg",
        img3: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8bmF0dXJlfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
        licensePlates: "29A-2224",
        brandName: "Toyota",
        productionYear: 2024,
        transmission: true,
        color: "White",
        model: "Camry",
        noOfSeats: 4,
        fuel: false, registrationPaper: "File1.PDF",
        certificateOfInspection: "File2.PDF",
        insurance: "File3.PDF",
        mileage: 15000,
        fuelConsumption: 500,
        address: "Hanoi, Hoang Mai, Hoang Mai",
        description: "Toyota Camry",
        functionsBluetooth: true,
        functionsGPS: false,
        functionsCamera: false,
        functionsSunRoof: false,
        functionsChildLock: false,
        functionsChildSeat: false,
        functionsDVD: false,
        functionsUSB: true,
        basePrice: 5000,
        requiredDeposit: 2000,
        noSmoking: true,
        noPet: true,
        noFoodInCar :false,
        other: false
    },
    {
        id: 4,
        name: "Toyota Camry",
        price: "600k",
        location: "Ba Dinh, Hanoi",
        img1: "https://www.toyota.com.vn//Resources/Images/F8B33019CF708D9157E8B8F633DDB447.png",
        img2: "https://www.toyota.com.vn//Resources/Images/EAE5157BACA728E302C7A2DB2D10B178.jpg",
        img3: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8bmF0dXJlfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
        licensePlates: "29A-2225",
        brandName: "Toyota",
        productionYear: 2025,
        transmission: true,
        color: "Brown",
        model: "Camry",
        noOfSeats: 4,
        fuel: true, registrationPaper: "File1.PDF",
        certificateOfInspection: "File2.PDF",
        insurance: "File3.PDF",
        mileage: 15000,
        fuelConsumption: 500,
        address: "Hanoi, Ba Dinh,Dao Tan",
        description: "Toyota Camry",
        functionsBluetooth: false,
        functionsGPS: false,
        functionsCamera: false,
        functionsSunRoof: false,
        functionsChildLock: false,
        functionsChildSeat: true,
        functionsDVD: false,
        functionsUSB: true,
        basePrice: 10000,
        requiredDeposit: 2000,
        noSmoking: true,
        noPet: true,
        noFoodInCar :false,
        other: false
    },
]